export const first_title = '.banner > h1'
export const section_title = '.product--va .col-7-12 >h2'
export const screens_number = '.product--va .product__stats > :nth-child(1) .stats__num '
export const screens_description = '.product--va .product__stats :nth-child(1) .stats__desc'
export const journeys_number = '.product--va .product__stats :nth-child(2) .stats__num'
export const journeys_description = '.product--va .product__stats :nth-child(2) .stats__desc'
export const get_in_touch_mail = '.mail'
export const twitter_button = '.footer__item .footer__media > :nth-child(1) > img'
export const linkedIn_button = '.footer__item .footer__media > :nth-child(2)'
export const facebook_button = '.footer__item .footer__media > :nth-child(3)'
export const twitter_userName = '[data-testid=UserName]'
export const twitter_accept = '#layers > div > div:nth-child(2) > div > div > div > div.css-1dbjc4n.r-eqz5dr.r-1joea0r.r-1r5su4o > div:nth-child(1) > div'
export const linkedIn_dismiss = '.modal__dismiss .contextual-sign-in-modal__modal-dismiss-icon >svg'
export const facebook_accept = ':nth-child(2) >.x1ypdohk .xozqiw3 .xl56j7k .x9f619 .x193iq5w .x1lliihq'
export const facebook_userName = '.x193iq5w >h1'
export const facebook_reload = '.xl56j7k >.x9f619 >.x193iq5w >.x1lliihq'
export const airportlabs_img = '.footer__copy >img'
