export const search_box = '#searchboxTrigger'
export const QNED_option = '.menu-container :nth-child(9) .filter-body :nth-child(4)'
export const three_stars_option = '[data-option-id="3-5"]'
export const sort_dropdown = '.sort-control-item :nth-child(2) .gtm_ejaugtrtnc .text-truncate'
export const descrescator_option = ':nth-child(4) > .js-sort-option'
export const add_to_cart_button = '.js-products-container > :nth-child(1) .card-v2-atc'
export const confirmation_message = '.modal-header .mrg-sep-none'
export const x_button = '.modal-header .em-close'
export const LG_option = '.sidebar-container-body > :nth-child(5) .js-scrollable > :nth-child(2)'
export const crescator_option = ':nth-child(3) > .js-sort-option'
export const detalii_cos_button = '.table-layout > :nth-child(3) > a'
export const cart_remote = '[data-id="199"] > .cart-widget > .main-product > .main-product-details-container > .line-item-main > .main-product-title-container > .line-item-title'
export const cart_TV = '[data-id="67990"] > .cart-widget > .main-product > .main-product-details-container > .line-item-main > .main-product-title-container > .line-item-title'
